apiVersion: v1
kind: Pod
metadata:
  name: oopservability-redis
  namespace: oopservability
  labels:
    app.kubernetes.io/name: oopservability-redis
    app.kubernetes.io/component: redis
spec:
  containers:
    - name: redis
      image: ghcr.io/magier/oopservability-redis:sha-b61e524
      imagePullPolicy: Always
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 128Mi
